/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fril;

import java.io.IOException;
import java.net.CookieManager;
import java.net.CookieStore;
import java.net.HttpCookie;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author CuongPhan
 */
public class FrmLogin extends javax.swing.JPanel {

    public static String FRIL_SIGNIN = "https://fril.jp/users/sign_in";
    public static String FRIL_HOMEPAGE = "https://fril.jp";
    public static String FRIL_ADDNEWITEM = "https://fril.jp/item";
    public static String USERNAME_EMPTY = "Username is empty, pls enter a username";
    public static String PASSWORD_EMPTY = "Password is empty, pls enter the password";
    public static String LOGIN_FAIL = "Invalid username or password";

    public String username = "";
    public String password = "";
    private String cookieId = "";                                  //to save the user cookie

    private String authenticityToken = "";
    private String gCookie = "";

    private CookieStore cookieStore = new CookieManager().getCookieStore();
    private CookieStore gCookieStore = new CookieManager().getCookieStore();

    /**
     * Creates new form FrmLogin
     * @throws java.io.IOException
     */
    public FrmLogin() throws IOException {  
        GetFrilHomePage();
        initComponents();
        loadAccount();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextField_Username = new javax.swing.JTextField();
        CheckBox = new javax.swing.JCheckBox();
        PasswordField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        lb_username = new javax.swing.JLabel();
        lb_password = new javax.swing.JLabel();
        lb_headline = new javax.swing.JLabel();

        setName("Login"); // NOI18N

        TextField_Username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TextField_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_UsernameActionPerformed(evt);
            }
        });

        CheckBox.setText("Remember Me");
        CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxActionPerformed(evt);
            }
        });

        PasswordField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Log in");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lb_username.setText("User Name:");

        lb_password.setText("Password:");

        lb_headline.setText("Log in with your email address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_headline, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(lb_username, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_Username, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_headline, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_username, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Login");
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_UsernameActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_TextField_UsernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (true == (Settings.rememberme) && !((Settings.cookie).isEmpty())) { //remember cookie
            //go directly to product management
        }
        if (TextField_Username.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jButton1, USERNAME_EMPTY, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (0 == PasswordField.getPassword().length) {
            JOptionPane.showMessageDialog(this, PASSWORD_EMPTY, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        username = TextField_Username.getText();
        password = new String(PasswordField.getPassword());

        try {
            Utility.logIn(FrmLogin.this, username, password);
        } catch (IOException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JCheckBox CheckBox;
    private javax.swing.JPasswordField PasswordField;
    public javax.swing.JTextField TextField_Username;
    public static javax.swing.JButton jButton1;
    private javax.swing.JLabel lb_headline;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel lb_username;
    // End of variables declaration//GEN-END:variables

    private void loadAccount() {
        if (Settings.rememberme) {
            TextField_Username.setText(Settings.username);
            PasswordField.setText(Settings.password);
            CheckBox.setSelected(true);
        }
    }

    private void GetFrilHomePage() throws MalformedURLException, IOException {
        String formUrl = FRIL_SIGNIN; // NOTE: This is the URL the form POSTs to, not the URL of the form (you can find this in the "action" attribute of the HTML's form tag
        if ((true == Settings.rememberme) && !(Settings.cookie.isEmpty())) { //remember cookie
            HttpCookie httpCookie = new HttpCookie("_fril_user_session", Settings.cookie);
            httpCookie.setDomain("fril.jp");
            cookieStore.add(null, httpCookie);
            cookieId = Settings.cookie;
        } else {

        }
        authenticityToken = Utility.getToken(formUrl);
    }

}
